(include_subdirs unqualified)

(library
 (name cornell_advanced_compilers_cs6120)
 (libraries
  base
  stdio
  core
  core_unix
  yojson
  ppx_sexp_conv
  ppx_compare
  ppx_hash
  ppx_enumerate
  ppx_deriving_yojson.runtime)
 (inline_tests)
 (preprocess
  (pps
   ppx_inline_test
   ppx_deriving.show
   ppx_deriving_yojson
   ppx_sexp_conv
   ppx_compare
   ppx_hash
   ppx_enumerate))
 )
