(tests
 (names
  test_lesson2
  test_basic_block
  test_bbs
  test_parse
  test_empty_cfg
  test_naming
  test_compile
  test_hash)
 (libraries
  lesson2
  base
  stdio
  yojson)
 (preprocess
  (pps
   ppx_deriving_yojson
   ppx_compare
   ppx_hash
   ppx_sexp_conv
   ppx_deriving.show))
 (flags
  :standard
  -warn-error
  -a))
